name: CI

on:
  push:
    branches: [ master ]
env:
  CHART_VERSION: "1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup yq
      run: |
        python -m pip install --upgrade pip
        sudo -H pip3 install yq
    - name: Install Helm 3
      uses: azure/setup-helm@v1
      with:
        version: v3.1.1
    - name: Build the helm chart
      id: helm_chart
      run: |
        export PATH=$PATH:~/.local/bin
        cd helm/eirini
        yq -yi '.version="'$CHART_VERSION.$GITHUB_RUN_NUMBER'"' Chart.yaml
        version=$(yq -r ".version" Chart.yaml)
        cd ..
        helm package eirini
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0-rc.2
      with:
        charts_dir: "helm" 
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
